version: '2'

services:
  sonarperl:
    image: sonarperl/sonar-perl
    ports:
    - "9000:9000"
  dancer:
    build: ./perl/Dancer
    environment:
      - SONAR_HOST_URL=http://ec2-54-79-178-102.ap-southeast-2.compute.amazonaws.com:9000
  sample:
    build: ./perl/sample-project
    environment:
      - SONAR_HOST_URL=http://ec2-54-79-178-102.ap-southeast-2.compute.amazonaws.com:9000
  mailslot4:
    build: ./perl/mailslot4
    environment:
      - SONAR_HOST_URL=http://ec2-54-79-178-102.ap-southeast-2.compute.amazonaws.com:9000
  mailslot5:
    build: ./perl/mailslot5
    environment:
      - SONAR_HOST_URL=http://ec2-54-79-178-102.ap-southeast-2.compute.amazonaws.com:9000
  mailslot6:
    build: ./perl/mailslot6
    environment:
      - SONAR_HOST_URL=http://ec2-54-79-178-102.ap-southeast-2.compute.amazonaws.com:9000
  mailslot7:
    build: ./perl/mailslot7
    environment:
      - SONAR_HOST_URL=http://ec2-54-79-178-102.ap-southeast-2.compute.amazonaws.com:9000
  mailslot8:
    build: ./perl/mailslot8
    environment:
      - SONAR_HOST_URL=http://ec2-54-79-178-102.ap-southeast-2.compute.amazonaws.com:9000
  mailslot9:
    build: ./perl/mailslot9
    environment:
      - SONAR_HOST_URL=http://ec2-54-79-178-102.ap-southeast-2.compute.amazonaws.com:9000

