version: '2'

services:
  sonarperl:
    image: sonarperl/sonar-perl
    ports:
    - "9000:9000"
  dancer:
    build: ./perl/Dancer
    environment:
      - SONAR_HOST_URL=http://ec2-13-238-217-10.ap-southeast-2.compute.amazonaws.com:9000
  sample:
    build: ./perl/sample-project
    environment:
      - SONAR_HOST_URL=http://ec2-13-238-217-10.ap-southeast-2.compute.amazonaws.com:9000
  mailslot4:
    build: ./perl/mailslot4
    environment:
      - SONAR_HOST_URL=http://ec2-13-238-217-10.ap-southeast-2.compute.amazonaws.com:9000
